mismatch = -3
gap      = -1
scoreMatrix = 'scoreMatrix.csv'
states={}
timedStates=[]
stateList=set()
emissionList=set()
reverseStartIndex=1
reverseEndIndex=7
csvFile = "data.csv"
inputcsv = "input.csv"
# csvFile = "training_set.csv"